debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.whatkinda.basicboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace  # spring boot 3.0 이상 버전부터 해당 프로퍼티 추가해줘야 basic binder 로깅 작동함
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format-sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
